FROM scratch

# ADD  --chown=107 https://dl.rockylinux.org/pub/rocky/10/BaseOS/x86_64/kickstart/images/pxeboot/initrd.img /initrd
# ADD  --chown=107 https://dl.rockylinux.org/pub/rocky/10/BaseOS/x86_64/kickstart/images/pxeboot/vmlinuz /vmlinuz

ADD --chown=107 https://repo.wcooke.me/rpm/rocky/10/images/pxeboot/initrd.img /initrd
ADD --chown=107 https://repo.wcooke.me/rpm/rocky/10/images/pxeboot/vmlinuz /vmlinuz
