FROM scratch

# ADD  --chown=107 https://mirrors.centos.org/mirrorlist?path=/10-stream/BaseOS/x86_64/os/images/pxeboot/initrd.img&redirect=1&protocol=https /initrd
# ADD  --chown=107 https://mirrors.centos.org/mirrorlist?path=/10-stream/BaseOS/x86_64/os/images/pxeboot/vmlinuz&redirect=1&protocol=https /vmlinuz

ADD  --chown=107 https://repo.wcooke.me/rpm/centos-stream/10/images/pxeboot/initrd.img /initrd
ADD  --chown=107 https://repo.wcooke.me/rpm/centos-stream/10/images/pxeboot/vmlinuz /vmlinuz
